--- 
- name: installing java
  raw: test -e /usr/bin/java || (apt -y update && apt install -y default-jre)
  register: output
  changed_when: output.stdout != ""

- name: Check for letsencrypt private key
  stat: path="/etc/letsencrypt/live/{{ ansible_domain_name }}/privkey.pem"
  become: yes
  register: existing_letsencrypt_key
  tags:
    - tls

- name: Check for letsencrypt cert
  stat: path="/etc/letsencrypt/live/{{ ansible_domain_name }}/cert.pem"
  become: yes
  register: existing_letsencrypt_cert
  tags:
    - tls


- name: Check for letsecnrypt upstream
  stat: path="/etc/letsencrypt/live/{{ ansible_domain_name }}/fullchain.pem"
  become: yes
  register: existing_letsencrypt_bundle
  tags:
    - tls


- name: Set Generation to false
  set_fact:
    generate_self_signed_certs: false
  when: 
    - existing_letsencrypt_key.stat.exists
    - existing_letsencrypt_cert.stat.exists
    - existing_letsencrypt_bundle.stat.exists

- name: Check for existing private key
  stat: path=/tmp/burp.key
  become: no
  when:
    - generate_self_signed_certs
  delegate_to: 127.0.0.1
  register: existing_key
  tags:
    - tls

- name: Check for existing PKCS8 private key
  stat: path=/tmp/{{ burp_key }}
  become: no
  when:
    - generate_self_signed_certs
  delegate_to: 127.0.0.1
  register: existing_pkcs8_key
  tags:
    - tls

- name: Check for existing CSR
  stat: path=/tmp/burp.csr
  become: no
  when:
    - generate_self_signed_certs
  delegate_to: 127.0.0.1
  register: existing_csr
  tags:
    - tls

- name: Check for existing certificate
  stat: path=/tmp/{{ burp_cert }}
  become: no
  when:
    - generate_self_signed_certs
  delegate_to: 127.0.0.1
  register: existing_cert
  tags:
    - tls

- name: Check for existing intermediate certificate
  stat: path=/tmp/{{ burp_ca_bundle }}
  become: no
  when:
    - generate_self_signed_certs
  delegate_to: 127.0.0.1
  register: existing_ca_bundle
  tags:
    - tls

- name: Generate private key
  command: openssl genrsa -out /tmp/burp.key 2048
  delegate_to: 127.0.0.1
  become: no
  when:
    - generate_self_signed_certs
    - not existing_key.stat.exists
  tags:
    - tls

- name: Convert RSA private key to PKCS8
  command: openssl pkcs8 -topk8 -inform PEM -in /tmp/burp.key -outform PEM -out /tmp/{{ burp_key }} -nocrypt
  delegate_to: 127.0.0.1
  become: no
  when:
    - generate_self_signed_certs
    - not existing_pkcs8_key.stat.exists
  tags:
    - tls

- name: Generate CSR
  command: openssl req -new -key /tmp/burp.key -out /tmp/burp.csr -subj "/C={{ country }}/ST={{ state }}/L={{ locality }}/O={{ organisation }}/OU={{ organisational_unit }}/CN=*.{{ ansible_domain_name }}"
  delegate_to: 127.0.0.1
  become: no
  when:
    - generate_self_signed_certs
    - not existing_csr.stat.exists
  tags:
    - tls
    - csr

- name: Create empty intermediate CA cert
  command: touch /tmp/{{ burp_ca_bundle }}
  delegate_to: 127.0.0.1
  become: no
  when:
    - generate_self_signed_certs
    - not existing_ca_bundle.stat.exists
  tags:
    - tls

- name: Generate self-signed certificate
  command: openssl x509 -req -sha256 -days 365 -in /tmp/burp.csr -signkey /tmp/burp.key -out /tmp/{{ burp_cert }}
  delegate_to: 127.0.0.1
  become: no
  when:
    - generate_self_signed_certs
    - not existing_cert.stat.exists
  tags:
    - tls
    - selfsign

- name: Set up directory for Burp jar
  file: dest=/usr/share/burp mode=0755 state=directory owner=root group=root
  tags:
    - setup

- name: Set up directory for Burp config
  file: dest=/etc/burp mode=0755 state=directory owner=root group=root
  tags:
    - setup

- name: Copy Burp jar
  copy: src={{ item }} dest=/usr/share/burp/burpsuite_pro.jar
  with_fileglob:
    - "{{ burp_file }}"
  tags:
    - installjar
    - setup

- name: Copy over server key
  copy: src=/tmp/{{ burp_key }} dest=/etc/burp/burp.pk8
  when:
    - generate_self_signed_certs
  tags:
    - setup

- name: Copy over server cert
  copy: src=/tmp/{{ burp_cert }} dest=/etc/burp/burp.crt
  when:
    - generate_self_signed_certs
  tags:
    - setup

- name: Copy over CA bundle certificates
  copy: src=/tmp/{{ burp_ca_bundle }} dest=/etc/burp/intermediate.crt
  when:
    - generate_self_signed_certs
  tags:
    - setup

- name: Copy letsencrypt key
  command: cp /etc/letsencrypt/live/{{ ansible_domain_name }}/privkey.pem /etc/burp/burp.pk8
  become: yes
  when:
    - not generate_self_signed_certs
  tags:
    - setup

- name: Copy letsencrypt cert
  command: cp /etc/letsencrypt/live/{{ ansible_domain_name }}/cert.pem /etc/burp/burp.crt
  become: yes
  when:
    - not generate_self_signed_certs
  tags:
    - setup

- name: Copy letsencrypt ca certificates
  command: cp /etc/letsencrypt/live/{{ ansible_domain_name }}/fullchain.pem /etc/burp/intermediate.crt
  become: yes
  when:
    - not generate_self_signed_certs
  tags:
    - setup


- name: Generate configuration file
  template: src={{ role_path }}/templates/burpcollaboratorconfig.jinja2 dest=/etc/burp/collaborator.config
  tags:
    - configure