---
# [allhosts]
# #allhostsingeneral 

# [burphosts]
# 10.0.3.152

all:
  hosts:
    ec2servers: 
    doservers: 
  children:
    ec2servers:
      hosts:
        aws1: 10.0.3.152
        aws2: 10.0.3.152
    doservers:
      hosts:
        do1: 10.0.3.152
        do2: 10.0.3.152
