---

- name: install Python utility packages
  become: true
  apt:
    name:
      - python3-pip
      - python3-virtualenv
      - python3-dev
      - virtualenv
  when: python3_pyenv == None

- name: requirements for pyenv install
  block:
    - name: install system packages required for pyenv
      apt:
        name:
          - curl
          - gcc
          - git
          - libbz2-dev
          - libreadline-dev
          - libssl-dev
          - libsqlite3-dev
          - make
          - zlib1g-dev
        state: present
  become: true
  when: python3_pyenv != None

- name: install python dependencies
  pip:
    name:
      - boto3
      - argparse
      - requests
      - pprint
      - re
      - random
  executable: pip3

- name: Get raw python source
  get_url:
    url: curl https://raw.githubusercontent.com/monoxgas/FlyingAFalseFlag/master/CloudRacoon/racoon_aws.py
    dest: /opt/cloudracoon.py
    mode: 0755

- name: alias cloudracoon and persist it in .bashrc
  shell: alias cloudracoon='python3 /opt/cloudracoon.py' ; echo "alias cloudracoon='python3 /opt/cloudracoon.py'" >> ~/.bashrc
  args:
    executable: /bin/bash

  