---
# Synchronize two directories on one remote host.
- name: push files from host to remote server
  synchronize:
    mode: push
    src: "{{ host_absolute_path }}"
    dest: "{{ remote_absolute_path }}"
    recursive: true
    verify_host: false
