---
- name: check for existing installation
  stat: 
    path: /opt/cobaltstrike
  become: yes
  register: cobaltstrike_installed

- name: debugging message is cs is already installed
  debug: 
    msg: "cobaltstrike is already installed"
  when:
    - cobaltstrike_installed.stat.exists


- name: apt update
  apt: 
    update_cache: yes
    upgrade: full
  become: yes
  when:
    - not cobaltstrike_installed.stat.exists

- name: add java 1.8 ppa
  apt_repository:
    repo: 'ppa:webupd8team/java'
  become: yes
  notify: 
  - apt update
  when:
    - not cobaltstrike_installed.stat.exists

- name: pre-accept java license
  debconf:
    name: "oracle-java8-installer"
    question: "shared/accepted-oracle-license-v1-1"
    value: "true" 
    vtype: "select" 
  become: true
  when:
    - not cobaltstrike_installed.stat.exists

- name: install java 1.8
  apt: 
    name: {{ item }} 
    state: installed
  become: yes
  with_items:
    - oracle-java8-installer
    - openssl
  when:
    - not cobaltstrike_installed.stat.exists

- name: unarchive the cobalstrike archive
  unarchive:
    src: "{{ cobaltstrike_file }}"
    dest: /opt/
  become: yes
  when:
    - not cobaltstrike_installed.stat.exists


#TODO Implement CS automatic certificate provisionioning
# - name: Checking if TLS certificates exist
#   stat: path="{{ cert_path }}"
#   register: tls_cert_present

# - name: Generating PKCS12 Keystore

#   when:
#     - tls_cert_present