---
# this is where all the magic happens. where we install python, ping, burp, etc

#   The most important file is roles/x/tasks/main.yml, here you define tasks, which 
#   will be executed, when role is executed.

# playbook example 
# - name: name  
#   hosts: web
#   vars: 
#     http_port: 80
#     max_clients: 200
#   remote_user: root

#   tasks:
#   - name: install httpd
#     apt: pkg=httpd state=latest
#   - name: write apache config
#     template: src=/srv/httpd.js dest=/etc/httpd.conf
#   - name: start httpd
#     service: name=httpd state=started

- name: install burp collaborator
  hosts: all
  user: root
  remote_user: user #this isthe connecting user
  sudo: yes #can also use become = yes to escalate 
  roles:
    - burp
  tasks: 
    #do we need to include tasks if e defined role?