---
# playbook example 
# - name: name  
#   hosts: web
#   vars: 
#     http_port: 80
#     max_clients: 200
#   remote_user: root

#   tasks:
#   - name: install httpd
#     apt: pkg=httpd state=latest
#   - name: write apache config
#     template: src=/srv/httpd.js dest=/etc/httpd.conf
#   - name: start httpd
#     service: name=httpd state=started

- name: install all packages
  hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - name: installing python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
  roles:
    - common
    #everything down will be dynamic
    # - burp
    # - cobaltstrike
    # - socat
    # - letsencrypt
    # - gophish
    # - nmap
    # - sqlmap
    # - sync-push
    # - sync-pull
