---
# this is where all the magic happens. where we install python, ping, burp, etc

#   The most important file is roles/x/tasks/main.yml, here you define tasks, which 
#   will be executed, when role is executed.

- name: Install python for Ansible 
  hosts: all
  gather_facts: false
  become: true
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
   
- name: Pings to make sure we alive 
  hosts: all
  tasks:
    - ping:

- name: Burp Collaborator Setup
  hosts: allhosts
  user: root
  remote_user: user
  sudo: yes
  roles:
    - burp