---
# Executes commands to remote server

- name: execute command to remote server
  shell: "{{ remote_command }}"
  args:
    executable: /bin/bash
  register: command

- debug: msg="{{ command.stdout_lines }}"
  when: command is succeeded

- debug: msg="{{ command.stderr_lines }}"
  when: command is failed
