---
# Executes commands to remote server

- name: execute command to remote server
  shell: "{{ remote_command }}"
  args:
    executable: /bin/bash
  register: command

- name: debug message for command success
  debug: 
    msg: "{{ command.stdout_lines }}"
  when: command is succeeded

- name: debug message for command failure
  debug: 
    msg: "{{ command.stderr_lines }}"
  when: command is failed
