--- 
- name: check for existing installation 
  stat: 
    path: /opt/empire
  become: yes
  register: empire_installed

- name: debug message for existing installation
  debug: 
    msg: "powershell empire is already installed"
  when:
    - empire_installed.stat.exists

- name: apt update
  apt: 
    update_cache: yes
    upgrade: full
  become: yes
  when:
    - not empire_installed.stat.exists

- name: ensure git is installed
  apt: 
    name: {{item}} 
    state: present
  with_items:
    - git
    - screen

- name: git clone of empire
  git: 
    repo: "https://github.com/EmpireProject/Empire"
    version: master
    dest: /opt/empire
    update: yes

- name: copying files for empire installation
  copy: 
    src: ../files/startup.rc
    dest: /opt/empire

- name: setup empire
  command: /opt/empire/setup/install.sh
  environment:
    STAGING_KEY: 'RANDOM'
  args:
    chdir: /opt/empire